server:
  port: 8089

spring:
    datasource:
        url: jdbc:mysql://192.168.98.128:3306/tpm
        username: admin
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20

    #配置redis
    redis:
        host: 192.168.98.128
        #redis密码，没有密码的可以用～表示
#        password: ~
        port: 6379
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000

    freemarker:
        request-context-attribute: req  #req访问request
        suffix: .ftl  #后缀名
        content-type: text/html
        enabled: true
        cache: false #缓存配置
        template-loader-path: classpath:/templates/ #模板加载路径 按需配置
        charset: UTF-8 #编码格式
        number_format: '0.##'   #数字格式化，无小数点
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#添加日志配置backLog
logging:
  file: F:\日志文件\SpringBootLog\logger.log  # 日志文件,绝对路径或相对路径
#  path:   保存日志文件目录路径
#  config:  日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
  level:  # 日志级别
    root: info
